### ISSUE TITLE
Upper browser content is not clickable

### ISSUE THREAD

**Issue by cornips** [cornips/flobro#11]
## Steps to Reproduce the Problem

  1. Open browser window with a webpage with an clickable item on top
  1. Click the item

## Expected Behavior
Webpage executing click

## Actual Behavior
Nothing, due to invisible action bar

## Specifications

  - Version: 0.1.2
  - Platform: Windows

**Comment by Exper1mental** [comment]
When should we expect a fix for this?

**Comment by cornips** [comment]
This will be fixed in the next release.
