### ISSUE TITLE
webcam and microphone support

### ISSUE THREAD

**Issue by mean-cj** [cornips/flobro#13]
hello

How i can enable or allow permission camera and mic on float window.
because cannot video call on float window.

thank.

**Comment by mean-cj** [comment]
ref: https://stackoverflow.com/questions/28089359/how-to-enable-camera-and-microphone-in-packaged-application-for-chrome-os-or-chr

**Comment by cornips** [comment]
Camera and mic permissions are currently unsupported in flobro, I will add this in the final release.

**Comment by cornips** [comment]
The current fix for this issue raised a lot of questions about global mic and camera permission. I have to further investigate mic and camera support.
https://developer.chrome.com/extensions/permission_warnings
