### ISSUE TITLE
Add Option to Disable 'Stay on top'

### ISSUE THREAD

**Issue by Exper1mental** [cornips/flobro#15]
Title pretty much sums it up. I'd very much appreciate a way to disable the 'stay on top' feature so that I can leave the popup on my desktop. I use this app to view my iOS Reminders on my Windows desktop but using my computer isn't practical when the app forces itself on top.

Being able to have multiple windows open would also be fantastic (as brought up by others). Then I could have the weather and some other important stuff sent right to my desktop.

Regardless, I think this is an excellent app and I hope you continue to develop it! 😃

**Comment by cornips** [comment]
Flobro was originally designed to be an always-on-top window. But I think your idea is a great addition to the app. And it would be useful when #8 is in production.

**Comment by cornips** [comment]
PR #68 will change the behavior from pin icon in title bar to toggle stay-on-top feature.
