### ISSUE TITLE
Action bar blocks UI

### ISSUE THREAD

**Issue by deanoakley** [cornips/flobro#19]
The first site I tried was broken due the to the app UI covering UI elements. Maybe this can slide above the window? See attached. 

![image](https://user-images.githubusercontent.com/28942588/49348580-f2736480-f6f1-11e8-8eb6-f6ade7190e2f.png)

**Comment by cornips** [comment]
This will be fixed in the next update 👍

**Comment by OlaMallaug** [comment]
I really like this App, but this bug makes the application useless for the pages I want to use it for. Any idea when you will release a fix for this?

**Comment by ghost** [comment]
> I really like this App, but this bug makes the application useless for the pages I want to use it for. Any idea when you will release a fix for this?

Same for me- the only site I want to use this for is blocked in this way and therefore this isn't workable for me.

**Comment by gabriel-felipe** [comment]
I'm not the maintainer of this project, but I'm just starting to use it. The solution I'm using is to use a special url and when loading from this url adding extra padding to my website, if you guys control the sites you want to use this feature on, this could be an option.
