### ISSUE TITLE
Geolocation API support

### ISSUE THREAD

**Issue by arnoldsandoval** [cornips/flobro#23]
**Description**
The browser/webview does not allow for geolocation.

**Steps to reproduce**
1. Go to any website that requires geolocation API. I am using hulu.com
2. Confirm that geolocation is not working/automatically declined

**Expected behavior**
You should be asked to authorize geolocation for the given page just as you would on a regular browser.

**Comment by cornips** [comment]
For now I won't be adding geolocation support.
Unfortunately, it is not possible within Chrome App API to request access to geolocation only when a website needs it. The whole application needs permission for this.
