### ISSUE TITLE
Default locale is dutch

### ISSUE THREAD

**Issue by lucasmerlin** [cornips/flobro#24]
Hi, the app is in Dutch for me instead of English. Seems like the problem is that the default locale in the manifest.json is nl. As a German I could successfully guess trough the menu but others might not be so lucky. 

Steps to Reproduce:
1. Change browser language to German or something else that is not English or Dutch. 
2. Open this extension.
3. Extension Settings are displayed in dutch.

**Expected behavior**
Extension menu should appear in English.

**Please complete the following information:**
 - OS: Windows
 - Version 0.1.2 beta

**Comment by cornips** [comment]
Good point! I will take look after the default locale, which should be English.

**Comment by ricardoboss** [comment]
Bump.
