### ISSUE TITLE
Fullscreen as pip

### ISSUE THREAD

**Issue by nandanraj56** [cornips/flobro#26]
Can you add a feature "like when we press fullscreen in any video(Ex youtube). It should become fullscreen in browser window not to whole pc screen.

**Comment by cornips** [comment]
Good point! If anyone knows a solution how to "fullscreen in a container", please help!

**Comment by cornips** [comment]
Removing fullscreen permission while allowing fullscreen in the events will fullscreen within the Flobro window, as @SilentBot1 implemented in [his fork](https://github.com/SilentBot1/flobro/commit/b96903732d25131c57c234f5f12bc47871e69b78#diff-4b1eb3dc48c4e16d49db5b42298fe654L24)
