### ISSUE TITLE
New Blocking/Inconvenience

### ISSUE THREAD

**Issue by yoHiThere** [cornips/flobro#34]
**Is your feature request related to a problem? Please describe.**
 This new update was great and solid, but now one thing that changed is that I will no longer be able to press enter to "save." Now I have to click "save"

**Describe the solution you'd like**
It was easy when I could just press enter to go to the link

**Describe alternatives you've considered**
Pressing TAB then ENTER

**Additional context**

**Comment by cornips** [comment]
Thank you for feature request. I will re-add support for the Enter key
