### ISSUE TITLE
Browser will not drag

### ISSUE THREAD

**Issue by EveU8** [cornips/flobro#35]
Since the update to FloBro the browser will no longer drag across the screen, you can only make the browser larger or smaller

Log into browser
Click and drag - nothing happens

I expect the browser to move to a position in the screen I would like

**Please complete the following information:**
 - OS: [e.g. Windows]
 - Version: [e.g. 0.2.0]

**Additional context**

**Comment by cornips** [comment]
The drag handle is now the favicon and document title.
I had to make this change to fix a bug with auto-hiding the title bar. I am aware this is not the best user experience, but I didn't find a better solution yet.
