### ISSUE TITLE
Shifting page content when menu is visible

### ISSUE THREAD

**Issue by mrozsebastian** [cornips/flobro#38]
**Describe the bug**
Page content being shifted when top menu is appearing.
Notice missing message box on screenshot .

**Steps to reproduce**
1. Launch Flobro
2. Enter any site
3. Get your cursor to the top of the application to trigger top menu

**Expected behavior**
 Webpage area should be adjusted to accommodate the appearing menu.

**Screenshots**
Before menu appears:
![Screenshot from 2019-07-20 17-51-31](https://user-images.githubusercontent.com/15183460/61580995-b83bc380-ab18-11e9-8c07-ce87d225df7a.png)
With menu:
![Screenshot from 2019-07-20 17-51-45](https://user-images.githubusercontent.com/15183460/61580996-b83bc380-ab18-11e9-92b3-06451f539074.png)

**Please complete the following information:**
 - OS: Linux Mint 19.1
 - Version: 0.2.0

**Additional context**
Non problematic on most web pages but with i.e. messenger leads to annoying waiting for top menu to disappear before being able to click on message box.

**Comment by cornips** [comment]
Thanks for your issue. Adjusting the height (instead of top position) of the webview when the menu appears is indeed a good option! That's one for the next release.
