### ISSUE TITLE
Title bar doesn't disappear

### ISSUE THREAD

**Issue by cornips** [cornips/flobro#42]
**Describe the bug**
The title bar has to slide up to disappear, but it stays fixed when you move your mouse over the drag area. This is annoying. Aspecially with #38 in mind.

**Steps to reproduce**
1. Slide on top of window to let title bar appear
2. Mouse over the document title and move mouse down or up
3. The bar now won't disappear again

**Expected behavior**
After moving the mouse out of the title bar, the bar should disappear.

**Please complete the following information:**
 - OS: Mac
 - Version: 0.2.0

**Additional context**
**QUICK FIX:** When you mouse over the action icons (minimize, settings, close) and then move your mouse out, the bar disappears correctly.

**Comment by cornips** [comment]
I can add a pin icon to the action icons to fix or unfix the title bar.

**Comment by yoHiThere** [comment]
yea I know, only when not maximized though. The only minimize/maximize option is the keyboard shortcut or is it not?

**Comment by cornips** [comment]
@yoHiThere You can maximize/restore by double clicking the title bar

**Comment by kpthomp1** [comment]
New title bar also leaves a thin 1px line at the top when hidden which you can see on dark backgrounds. Was not present in 0.1.2.

**Comment by PMO4** [comment]
Noticed this issue too, bar hides inconsistently.  I'm using FB for a very small monitoring window so it makes a big difference when the title bar doesn't retreat.
