### ISSUE TITLE
Alternative native chrome PIP (Picture-in-Picture)

### ISSUE THREAD

**Issue by ricardoboss** [cornips/flobro#46]
Hi, first of all I want to express what a nice extension this is! Good job!

I think it's important to look at some alternatives (or at least know that there are any) before using an external tool or extension. This is why I want to highlight the native chrome implementation of this extension: Picture-in-Picture.

If you didn't know, chrome supports Picture-in-Picture natively for every `<video>` tag. In older chrome versions, you had to enable this feature by turning the `chrome://flags#enable-surfaces-for-videos` flag on first. Since version 70, this is enabled by default (if you don't have this feature, you need to update your chrome version).

When you right click on a `<video>` on a given website, you can click on "Picture in picture" and a new window playing the video opens and is always on top (even above other windows, like you would expect):

![image](https://user-images.githubusercontent.com/6266356/63579991-16cee400-c594-11e9-98a9-73c70cb5980d.png)

This isn't a real issue, I just wanted to highlight other options instead of using an extension.

Thanks for you attention!

**Comment by cornips** [comment]
This is great, but only works for (HTML5) videos. If you want to have a webpage as PIP, you can use Flobro.
