### ISSUE TITLE
Bad URL recognition

### ISSUE THREAD

**Issue by jeidsoter** [cornips/flobro#48]
The application cannot recognize URL links without end domain tag (.com, eu ...)
So if you have for example URL with port in it, (http://hesta-abra:8081), this URL cannot be added.

**Comment by cornips** [comment]
Good one! This should be supported, so I will work on it!

**Comment by donkawechico** [comment]
+1 for this feature! If it matters, my use-case is that I have a self-hosted security cam web server that I like to have up for catching deliveries, seeing who's at the door, making sure the cat doesn't escape, etc.

**Comment by shaulnaim** [comment]
trying to open localhost:4200 and get "the entered value is not recognized as a valid URL"  any idea how to solve?

**Comment by cornips** [comment]
Merging to #55
