### ISSUE TITLE
Can you please make an option called, "never show title bar?"

### ISSUE THREAD

**Issue by yoHiThere** [cornips/flobro#51]
**Is your feature request related to a problem? Please describe.**
I don't like when I go back into the floating window and the title bar appears every time. The only problem this has is what I want to do in the furture

**Describe the solution you'd like**
In the options, please add the option

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by cornips** [comment]
We need the title bar to allow the window to be dragged.
A keyboard shortcut could toggle the title bar, but I'm not sure if people understand this when they accidentally turn on such option.

**Comment by cornips** [comment]
Revisit this for UI improvement in #6
