### ISSUE TITLE
Some URL's are rejected.

### ISSUE THREAD

**Issue by palindali** [cornips/flobro#55]
The app rejects some URL's while they are valid ones.
An example is: https://player.twitch.tv/?channel=firedragon&enableExtensions=true&muted=false&player=popout&volume=0.38
is rejected, although it is a valid twitch.tv link.

**Comment by desi9n** [comment]
Next example: http://localhost:8383/example/page.php

**Comment by Haidafraid** [comment]
Another example of rejected URLs are those that include basic authentication credentials. 
Like:
https://user:password@domain.tld

**Comment by cornips** [comment]
Also failing: http://hesta-abra:8081 as submitted in #48
