### ISSUE TITLE
So how do you start that????

### ISSUE THREAD

**Issue by susannegraz** [cornips/flobro#58]
Installed it but there is no way to open a new window. No description, nothing.

**Comment by cornips** [comment]
After installation you can open Flobro by searching for it in Menu Start (Windows) or Spotlight (Mac).
When Flobro opens for the first time, the options window is shown where you can enter a URL. After clicking "save" the browser window is opened.

If you want a shortcut to Flobro in your taskbar, drag the icon from the Menu Start or Spotlight to you taskbar.

**Comment by CaptainPalapa** [comment]
Yeah, every time I close my Flobro window, I have to re-learn how to get it open again.  But at least it remembers the URL!  I only use it to watch my solar / electrical system on our RV.
