### ISSUE TITLE
Must visit Chrome Store to launch this app

### ISSUE THREAD

**Issue by David263** [cornips/flobro#70]
**Describe the bug**
Must visit Chrome Store to launch this app. Too difficult to get it running. Once it runs, it's useful. Also, I heard that apps are being eliminated in favor of extensions in Chrome. Extensions can't generate title-less windows. I've read all the text that comes with flobro. No way to launch it.

**Steps to reproduce**
1. Go to any part of the Windows desktop or the Chrome browser.
2. Try to find a way to launch flobro.
3. Give up eventually.

**Expected behavior**
There should be a button or something to launch flobro.

**Screenshots**

**Environment variables:**
 - OS:  Windows Home
 - Version: doesn't have a version
 - Chrome version: e.g. 85.0.4183.83

**Additional context**

**Comment by cornips** [comment]
Hello and thanks for your issue!
Because Flobro is a Chrome App and not an extension, you can launch it from your Start Menu on Windows or Spotlight on Mac. Does that help you?
Chrome is indeed shutting down Chrome App support, therefor we're converting to an electron app in issue #6

**Comment by David263** [comment]
To answer your question, the Start button on Windows launches a strange environment that has had various names, featuring colored panes that can act as buttons or displays. I almost never use Start or its Metro or Modern interface, which is tuned to run on touchscreens. I am a computer developer, so I don't use touchscreens, I use keyboards, mouse, and the Windows desktop interface. I need efficiency to get stuff done. So, no, if blobro can be launched through the Start button (which is poorly documented), it is useless to me.

I wanted to create windows without title bars on most OSes so I could display tiny digital clocks. I found very few ways to do this, one of which was Electron. Electron is no good, though, because a minimal Electron app on Windows creates 4 heavy Windows processes using a total of 60 MB of memory. There used to be a product variously called Neutralino or NeutralinoJS that attempted to solve this problem but it was abandoned. I think there is currently no simple product that generates a title-less window on any OS, exposing an API that apps can call. Electron does work, but it's a hog.

Also a hog is the Go language. It is a wonderful language in many ways. But its linker is primitive and does static linking only, in large chunks. The overhead of the Go runtime library is roughly 700 KB. When the "formatting" part of the runtime library is imported, the entire code for all possible formatting is linked in, so the official simple formatted "hello world" test program generates a 1.9 MB executable file, when it should be about 4 KB!

I wish you the best of luck porting flobro elsewhere. I doubt it can be done efficiently and nicely, thanks in part to the pressure caused by malicious users who want to do easy phishing.

**Comment by cornips** [comment]
To open Flobro in Windows with just the keyboard, the following should do it:

- Hit Windows key
- Type "Flobro"
- Hit Enter key

**Comment by David263** [comment]
Those instructions do not happen to work for me, since I have disabled Cortana (the Windows assistant) completely. I did this because it was using so much cpu power that my fan was struggling to keep the chip from burning up.

Do you have any feedback from me concerning the advice I gave? You seem to be silent now.

I don't really need to run flobro myself, but I was submitting this problem report on behalf of all those Windows users who, like me, only use the desktop interface.

For everyone else, I am happy that flobro works well for them (until Chrome eliminates apps). I love how it works; it is useful and pretty at the same time. It shows unusually good and user-friendly design.
