### ISSUE TITLE
Can't 2-finger scroll once title bar hides

### ISSUE THREAD

**Issue by codador** [cornips/flobro#73]
**Describe the bug**
I use flobro to show a google doc, like a sticky note. With 0.2.4, I can no longer 2-finger (touchpad) scroll the doc, once the title bar auto-hides.

**Steps to reproduce**
1. Hover mouse over window.
2. Title bar is visible: see 2-finger scrolling work.
3. Don't move mouse, wait for title bar to auto-hide.
4. Title bar is hidden: see 2-finger scrolling not work.

**Expected behavior**
2-finger scrolling should work, like in 0.2.3.

**Screenshots**

**Environment variables:**
 - OS: ChromeOS, Mac
 - Version: 0.2.4
 - Chrome version: 84.0.4147.136

**Additional context**
0.2.3 worked fine. This issue happens when pinned or unpinned.

**Comment by cornips** [comment]
Thank you for your issue. Very clear description of the bug 👍. I will investigate this further.

**Comment by cornips** [comment]
Fixed in 7d200b2
