### ISSUE TITLE
Not rendering local html file

### ISSUE THREAD

**Issue by czechtech** [cornips/flobro#77]
**Describe the bug**
I set the URL to "file:///home/chronos/u-f003.../MyFiles/Downloads/page.html"  Flobro does not render it.  The Flobro window remains an empty white.

**Steps to reproduce**
1. Create an HTML file in a Chromebook's Download folder.
2. Open it in Chrome by right-clicking on the file and choose "View."
3. Copy the URL from Chrome's address bar.
4. Set the URL in Flobro

**Expected behavior**
I created a super simple html page and expected Flobro to display it.

**Environment variables:**
 - OS: Chromebook
 - Version: 85.0.4183.84 (Official Build) (64-bit)

**Comment by cornips** [comment]
I was able to reproduce this. This has to do with the [Content Security Policy](https://developer.chrome.com/apps/contentSecurityPolicy#what), and unfortunately Google has restricted it for Chrome Apps so I cannot expand it. Therefor we're not able to allow Flobro accessing local files. 😔
