### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by cornips** [cornips/flobro#8]
A Chrome user requested this feature to have multiple windows.

> I need to build a dashboard and this window is just what I needed! Can I get multiple instances with different URLs running?

**Comment by Booligoosh** [comment]
Yes please! 😍

**Comment by Exper1mental** [comment]
Please do! I would be ecstatic if this app could have that functionality.

**Comment by procopsamuraev** [comment]
+1 for multiply instances

**Comment by bromelio** [comment]
What's better than a flobro window? **Several** flobro windows! Please add this feature, yes!

**Comment by bromelio** [comment]
Pennywise already did it: [https://github.com/kamranahmedse/pennywise/releases](url)

**Comment by cornips** [comment]
Continuing this issue in #61
