### ISSUE TITLE
Camera and Microphone Cannot Be Enabled - e.g. on Google Meet

### ISSUE THREAD

**Issue by daamonparker** [cornips/flobro#84]
For my first use of FloBro, I wanted to use https://meet.google.com/ to create a new immediate meeting - all appears well except that the camera and microphone are disabled and there's no apparent way to enable them. Normally, it's a case of clicking the camera icon at the end of the URL address bar but that's not visible in FloBro.

**Comment by pkvdesigns** [comment]
I have the same problem. Would love to be able to have a floating Google Meet screen. But need Camera and microphone access.

**Comment by sjarrossay** [comment]
Me too same problem and same need.

**Comment by viaahmed** [comment]
Yeah, same problem with me. @cornips  your app doesn't have any alternatives, so please consider to resolves issues quicker, thanks for developing the app.

**Comment by anjum121** [comment]
I thought it would be an option, I would love to have this as microsoft teams required audio and video feature

**Comment by spkane** [comment]
Given that this issue has been open for about 6 months with no developer comment. Is there any chance that we can get some idea from @cornips on how hard this might be to fix and wether it is something that you are planning on fixing, or if it is something you are looking for a PR to fix?

**Comment by cornips** [comment]
Camera and microphone are not allowed in Flobro Chrome App. If we want to allow that, the app needs permissions to camera and microphone. This caused a lot of concerns as people had to allow permanent access.
I don't see implementation of cam and mic happening in the Chrome App for now.
See https://github.com/flobro/flobro-chrome-app/issues/13#issuecomment-513936623
