### ISSUE TITLE
Invitation to make a similar plugin for Obsidian.md

### ISSUE THREAD

**Issue by viaahmed** [cornips/flobro#87]
**Is your feature request related to a problem? Please describe.**
I introduce you to this app Obsidian.md  It is a out-of-box note taking app.

**Describe the solution you'd like**
I invite you to write a plugin for this app, by which user may fix a note to be always on top.

**Describe alternatives you've considered**.
N.A.
**Additional context**
Your contribution would be definitely appreciated, if god wills.

**Comment by cornips** [comment]
Out of scope
