### ISSUE TITLE
Switching to settings window doesn't work

### ISSUE THREAD

**Issue by cornips** [cornips/flobro#9]
Keyboard shortcuts Esc or CTRL + N do not work when focused on content of web window.

## Expected Behavior
The settings window displayed on screen.

## Actual Behavior
Nothing

## Steps to Reproduce the Problem

  1. Open the app with a URL already set (app opens directly in browser mode)
  1. Drag the browser window (this wil focus the window)
  1. Enter Esc or CTRL + N on your keyboard to open the settings

## Specifications

  - Version: 0.1.0
  - Platform: Windows 10

**Comment by cornips** [comment]
**Workaround**: click and drag the minimize button, then you can use Esc or CTRL + N

**Comment by cornips** [comment]
Fixed in release [0.1.2](https://github.com/cornips/flobro/releases/tag/0.1.2)

**Comment by yoHiThere** [comment]
ctrl n adds a tab for me?
also can you make esc not a shortcut cause it's commonly used it would go to settings if there is settings but the use of esc doesn't work! I can't use esc anymore
